// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CaptainWatch.Api.Repository.Db.EntityFramework.Objects;

public partial class ExtraUserInformation
{
    public int Id { get; set; }

    public int UserId { get; set; }

    public string FullName { get; set; }

    public bool? IsPublic { get; set; }

    public string Email { get; set; }

    public string Localisation { get; set; }

    public string Bio { get; set; }

    public string ApiPass { get; set; }

    public string UserLanguage { get; set; }

    public bool? ViewParam { get; set; }

    public DateTime? FirstActivity { get; set; }

    public DateTime? LastActivity { get; set; }

    public DateTime? FirstRecoActivity { get; set; }

    public string HomeHulkVersion { get; set; }

    public string Title { get; set; }

    public DateTime? Birthdate { get; set; }

    public bool? BirthdateEstimated { get; set; }

    public DateTime? Step1Filled { get; set; }

    public string AhaMomentMode { get; set; }

    public DateTime? BeginRatingDate { get; set; }

    public bool? InternalEmailValid { get; set; }

    public bool? UnsubscribedAllMail { get; set; }

    public bool? FirstRecoActivityEstimated { get; set; }

    public bool? EmailOpened { get; set; }

    public bool? EmailClicked { get; set; }

    public bool? FirstRecoSkipped { get; set; }

    public string FbFirstName { get; set; }

    public string FbLastName { get; set; }

    public string FbName { get; set; }

    public string FbAgeRange { get; set; }

    public string FbLink { get; set; }

    public string FbGender { get; set; }

    public string FbId { get; set; }

    public bool AbTestingSubscription { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public DateTime? LastNotifConsult { get; set; }

    public string WProfil { get; set; }

    public DateTime? LastWatchListConsult { get; set; }

    public DateTime? LastActivityAppiOs { get; set; }

    public bool? EmailSpamComplaint { get; set; }

    public double? UserScore { get; set; }

    public string UserFacebook { get; set; }

    public string UserInstagram { get; set; }

    public string UserTwitter { get; set; }

    public string UserYoutube { get; set; }

    public string UserSnapchat { get; set; }

    public bool? ActivityVip { get; set; }

    public virtual UserProfile User { get; set; }
}