// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CaptainWatch.Api.Repository.Db.EntityFramework.Objects;

public partial class List
{
    public int Id { get; set; }

    public string Name { get; set; }

    public int Votes { get; set; }

    public int CreatorUserId { get; set; }

    public DateTime CreatedDate { get; set; }

    public DateTime UpdatedDate { get; set; }

    public bool IsRanked { get; set; }

    public int? ViewsPublic { get; set; }

    public int? Views { get; set; }

    public string BackgroundElementType { get; set; }

    public int? BackgroundElementId { get; set; }

    public string TechId { get; set; }

    public string TechType { get; set; }

    public string TechName { get; set; }

    public string TechValue { get; set; }

    public bool IsPrivate { get; set; }
}