// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CaptainWatch.Api.Repository.Db.EntityFramework.Objects;

public partial class Movie
{
    public int Id { get; set; }

    public string ImdbId { get; set; }

    public string OriginalTitle { get; set; }

    public string Title { get; set; }

    public string RealOriginalTitle { get; set; }

    public string Overview { get; set; }

    public double? Popularity { get; set; }

    public long? Revenue { get; set; }

    public long? Budget { get; set; }

    public string Status { get; set; }

    public string Tagline { get; set; }

    public double? VoteAverage { get; set; }

    public int? VoteCount { get; set; }

    public string BackdropPath { get; set; }

    public string PosterPath { get; set; }

    public string PosterPathFr { get; set; }

    public DateTime? ReleaseDate { get; set; }

    public DateTime? ReleaseDateFr { get; set; }

    public DateTime? MinReleaseDate { get; set; }

    public string OverviewFr { get; set; }

    public string TaglineFr { get; set; }

    public int? DominantColorR { get; set; }

    public int? DominantColorG { get; set; }

    public int? DominantColorB { get; set; }

    public double SiteVoteAverage { get; set; }

    public int SiteVoteCount { get; set; }

    public DateTime LastUpdate { get; set; }

    public int? BelongsToCollection { get; set; }

    public double? ImdbRating { get; set; }

    public int? ImdbNumVotes { get; set; }

    public DateTime? ImdbLastUpdate { get; set; }

    public int? Time { get; set; }

    public string BlogUrl { get; set; }

    public DateTime? ItunesLastUpdate { get; set; }

    public int? DominantOriginalColorR { get; set; }

    public int? DominantOriginalColorG { get; set; }

    public int? DominantOriginalColorB { get; set; }

    public bool? IsFrench { get; set; }

    public string Certification { get; set; }

    public string CertificationFr { get; set; }

    public bool? Video { get; set; }

    public double? ComingSoonRating { get; set; }

    public string ImdbCertificate { get; set; }

    public string ImdbCertificateFr { get; set; }

    public int? WatchlistCount { get; set; }

    public bool? NetflixAvailability { get; set; }

    public DateTime? NetflixAvailabilityDate { get; set; }

    public bool? FRated { get; set; }

    public bool? TripleFRated { get; set; }

    public bool? ImdbAnime { get; set; }

    public int? CollectionPosition { get; set; }

    public DateTime? CncLastUpdate { get; set; }

    public string NetflixId { get; set; }

    public bool? Wplay { get; set; }

    public int? TheaterCountFr { get; set; }

    public string MainTrailer { get; set; }

    public DateTime? CreatedDate { get; set; }

    public double? SiteScore { get; set; }

    public double? SiteScorePast { get; set; }

    public double? SiteScorePresent { get; set; }

    public double? SiteScoreFuture { get; set; }
}