// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CaptainWatch.Api.Repository.Db.EntityFramework.Objects;

public partial class Person
{
    public int Id { get; set; }

    public string Biography { get; set; }

    public DateTime? Birthday { get; set; }

    public DateTime? Deathday { get; set; }

    public string Name { get; set; }

    public string PlaceOfBirth { get; set; }

    public string ProfilePath { get; set; }

    public DateTime LastUpdate { get; set; }

    public int? Gender { get; set; }
}