// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CaptainWatch.Api.Repository.Db.EntityFramework.Objects;

public partial class Tv
{
    public int Id { get; set; }

    public string ImdbId { get; set; }

    public int? TvdbId { get; set; }

    public string Name { get; set; }

    public string OriginalName { get; set; }

    public string RealOriginalName { get; set; }

    public string BackdropPath { get; set; }

    public DateTime? FirstAirDate { get; set; }

    public DateTime? LastAirDate { get; set; }

    public DateTime? NextAirDate { get; set; }

    public string Homepage { get; set; }

    public bool? InProduction { get; set; }

    public int? NumberOfEpisodes { get; set; }

    public int? NumberOfSeasons { get; set; }

    public string Overview { get; set; }

    public string OverviewFr { get; set; }

    public double? Popularity { get; set; }

    public string PosterPath { get; set; }

    public string PosterPathFr { get; set; }

    public string Status { get; set; }

    public double? VoteAverage { get; set; }

    public int? VoteCount { get; set; }

    public double SiteVoteAverage { get; set; }

    public int SiteVoteCount { get; set; }

    public DateTime LastUpdate { get; set; }

    public double? ImdbRating { get; set; }

    public int? ImdbNumVotes { get; set; }

    public DateTime? ImdbLastUpdate { get; set; }

    public string ItunesArtistId { get; set; }

    public DateTime? ItunesLastUpdate { get; set; }

    public bool? NetflixAvailability { get; set; }

    public DateTime? NetflixAvailabilityDate { get; set; }

    public int? NetflixSeasonCount { get; set; }

    public DateTime? NetflixSeasonUpdate { get; set; }

    public bool? CanalplayAvailability { get; set; }

    public DateTime? CanalplayAvailabilityDate { get; set; }

    public int? WatchlistCount { get; set; }

    public bool? ImdbAnime { get; set; }

    public string NetflixId { get; set; }

    public string MainTrailer { get; set; }

    public DateTime? CreatedDate { get; set; }

    public double? SiteScore { get; set; }

    public double? SiteScorePast { get; set; }

    public double? SiteScorePresent { get; set; }

    public double? SiteScoreFuture { get; set; }

    public int? LastEpisodeToAirNumber { get; set; }

    public int? LastEpisodeToAirSeason { get; set; }

    public int? NextEpisodeToAirNumber { get; set; }

    public int? NextEpisodeToAirSeason { get; set; }
}