// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CaptainWatch.Api.Repository.Db.EntityFramework.Objects;

public partial class UserProfile
{
    public int UserId { get; set; }

    public string UserName { get; set; }

    public Guid UserGuid { get; set; }

    public virtual ICollection<ExtraUserInformation> ExtraUserInformation { get; set; } = new List<ExtraUserInformation>();
}