// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CaptainWatch.Api.Repository.Db.EntityFramework.Objects;

public partial class Wish
{
    public int Id { get; set; }

    public int MovieId { get; set; }

    public int UserId { get; set; }

    public bool Positive { get; set; }

    public DateTime? CreatedDate { get; set; }
}